version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: coding-sensai-db.cvwyum8mo77b.us-east-1.rds.amazonaws.com
