/*
CREATE TABLE "code_examples" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" INTEGER NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "course" VARCHAR(100),
  "created_at" TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY ("topic_id") REFERENCES "topics" ("id") ON DELETE CASCADE
);

CREATE TABLE "code_example_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code_example_id" INTEGER NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "content" TEXT,
  "created_at" TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY ("code_example_id") REFERENCES "code_examples" ("id") ON DELETE CASCADE
);

*/
const { initPool } = require("../config/db");

const pool = initPool();

// So we need a function to fetch all code examples for a given topic_id
const get_code_by_id = async (code_id) => {
    try {
        const result = await pool.query(`
            SELECT
                c.id as code_id,
                c.title as code_title,
                c.description as code_description,
                cc.id as code_content_id,
                cc.title as code_content_title,
                cc.content as code_content
            FROM code_examples c
            JOIN code_example_codes cc ON c.id = cc.code_example_id
            WHERE c.id = $1
        `, [code_id]);

        if (result.rows.length === 0) {
            throw new Error("Code example not found.");
        }

        return result.rows[0];
    } catch (err) {
        throw err;
    }
}



module.exports = {
    get_code_by_id
};


