/*
CREATE TABLE "topics" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" INTEGER NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "order" INTEGER NOT NULL,
  "total_markers" INTEGER NOT NULL,
  "created_at" TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE
);


-- Topic resources
CREATE TABLE "resources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" INTEGER NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "url" VARCHAR(200),
  "type" resource_type NOT NULL,
  "created_at" TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY ("topic_id") REFERENCES "topics" ("id") ON DELETE CASCADE
);
*/
const { initPool } = require("../config/db");

const pool = initPool();

// So we need a function to fetch all resources for a given topic_id
const fetch_resource_by_topic_id = async (topic_id) => {
    try {
        const resources = await pool.query(`
           SELECT
                r.id as resource_id,
                r.title as resource_title,
                r.url as resource_url,
                r.type as resource_type
            FROM resources r
            WHERE r.topic_id = $1    
        `, [topic_id]);

        return resources.rows;

    } catch (err) {
        throw err;
    }
}



module.exports = {
    fetch_resource_by_topic_id
};