name: Deploy Lambda Function

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js (if you're using a Node.js Lambda function)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version that matches your Lambda runtime

# I already removed the depolyment so no need to push to aws
# but I will just leave it as it is.
